In [1]:
import pandas as pd

### Electricity prices for household consumers - bi-annual data (from 2007 onwards)
Europe

In [2]:
# df = pd.read_csv("data/nrg_pc_204_c_linear.csv")
df = pd.read_csv("data/nrg_pc_204_linear-electricity_prices_household.csv")
df

,DATAFLOW,LAST UPDATE,freq,product,consom,unit,tax,currency,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG
0,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2011-S1,0.1152,NaN
1,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2011-S2,0.1157,NaN
2,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2012-S1,0.1163,NaN
3,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2012-S2,0.1167,NaN
4,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2013-S1,0.1156,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
48175,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,X_VAT,PPS,UK,2018-S1,0.1325,NaN
48176,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,X_VAT,PPS,UK,2018-S2,0.1452,NaN
48177,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,X_VAT,PPS,UK,2019-S1,0.1453,NaN
48178,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,X_VAT,PPS,UK,2019-S2,0.1553,NaN
48179,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,X_VAT,PPS,UK,2020-S1,0.1554,NaN

- AL: Albania
- All taxes and levies included
- currency: EUR

In [7]:
df.geo.unique()
# df.loc[(df.geo == 'AL') & (df.freq == 'A')]
# df.loc[(df.geo == 'AL') & (df.TIME_PERIOD == '2011-S1') & (df.currency == 'EUR')]
df.loc[(df.geo == 'AL') & (df.tax == 'I_TAX') & (df.currency == 'EUR')]

,DATAFLOW,LAST UPDATE,freq,product,consom,unit,tax,currency,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG
0,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2011-S1,0.1152,NaN
1,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2011-S2,0.1157,NaN
2,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2012-S1,0.1163,NaN
3,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2012-S2,0.1167,NaN
4,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161901,KWH,I_TAX,EUR,AL,2013-S1,0.1156,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
38562,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,I_TAX,EUR,AL,2019-S1,0.0920,e
38563,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,I_TAX,EUR,AL,2019-S2,0.0933,NaN
38564,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,I_TAX,EUR,AL,2020-S1,0.0922,e
38565,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,I_TAX,EUR,AL,2020-S2,0.0920,e
38566,ESTAT:NRG_PC_204(1.0),27/06/22 23:00:00,S,6000,4161905,KWH,I_TAX,EUR,AL,2021-S2,0.0937,NaN

In [11]:
df.TIME_PERIOD.unique()

array(['2017', '2018', '2019', '2020', '2021', '2015-S2', '2016-S2',
       '2008-S2', '2009-S2', '2010-S2', '2011-S2', '2012-S2', '2013-S2',
       '2014-S2', '2007-S2'], dtype=object)

### US, states, monthly

In [3]:
df = pd.read_csv("data/us/Average_retail_price_of_electricity.csv")
df

,description,units,source key,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,...,Sep 2021,Oct 2021,Nov 2021,Dec 2021,Jan 2022,Feb 2022,Mar 2022,Apr 2022,May 2022,Jun 2022
0,Average retail price of electricity,cents per kilowatthour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,United States,NaN,ELEC.PRICE.US-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,New England,cents per kilowatthour,ELEC.PRICE.NEW-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,New England : all sectors,cents per kilowatthour,ELEC.PRICE.NEW-ALL.M,10.73,10.53,10.72,10.84,10.61,11.03,11.83,...,18.86,18.36,18.39,18.86,19.98,21.20,20.31,19.95,19.43,20.26
4,New England : residential,cents per kilowatthour,ELEC.PRICE.NEW-RES.M,11.80,11.72,11.82,12.17,12.20,12.19,12.50,...,22.20,21.91,21.87,22.04,22.83,24.63,24.50,24.47,23.81,24.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,Pennsylvania : residential,cents per kilowatthour,ELEC.PRICE.PA-RES.M,8.74,9.01,9.29,9.38,9.98,10.63,10.32,...,14.10,14.53,14.17,14.37,14.19,14.48,14.70,14.93,15.20,16.51
75,Pennsylvania : commercial,cents per kilowatthour,ELEC.PRICE.PA-COM.M,7.99,8.30,8.51,8.60,8.93,9.41,8.86,...,9.08,9.31,9.66,9.68,9.63,10.13,9.89,10.14,10.51,11.05
76,Pennsylvania : industrial,cents per kilowatthour,ELEC.PRICE.PA-IND.M,5.93,5.21,5.47,5.82,5.63,5.84,5.96,...,6.85,6.96,7.28,6.96,7.52,7.67,7.31,7.54,8.08,8.53
77,Pennsylvania : transportation,cents per kilowatthour,ELEC.PRICE.PA-TRA.M,--,--,--,--,--,--,--,...,6.28,6.87,6.52,6.40,7.14,6.91,6.73,7.78,7.63,8.29
78,Pennsylvania : other,cents per kilowatthour,ELEC.PRICE.PA-OTH.M,8.54,10.50,9.51,7.81,13.49,13.21,13.08,...,--,--,--,--,--,--,--,--,--,--