In [5]:
import pandas as pd
import numpy as np

### US, states, monthly

In [9]:
df = pd.read_csv("data/us/Average_retail_price_of_electricity_states.csv")
df

,description,units,source key,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,...,Sep 2021,Oct 2021,Nov 2021,Dec 2021,Jan 2022,Feb 2022,Mar 2022,Apr 2022,May 2022,Jun 2022
0,United States,NaN,ELEC.PRICE.US-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,New England,NaN,ELEC.PRICE.NEW-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Connecticut,cents per kilowatthour,ELEC.PRICE.CT-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Connecticut : all sectors,cents per kilowatthour,ELEC.PRICE.CT-ALL.M,9.76,9.06,9.38,9.61,9.57,9.56,9.78,...,19.62,18.90,18.51,18.55,19.90,23.20,20.77,22.22,20.49,21.49
4,Connecticut : residential,cents per kilowatthour,ELEC.PRICE.CT-RES.M,10.70,10.23,10.60,10.87,11.20,11.06,11.00,...,22.42,22.85,21.35,20.85,22.28,26.48,25.61,27.10,24.81,25.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,Hawaii : residential,cents per kilowatthour,ELEC.PRICE.HI-RES.M,16.94,16.73,16.58,16.19,16.30,16.38,16.62,...,34.30,34.28,34.57,35.57,37.44,38.15,39.97,41.57,43.11,44.09
364,Hawaii : commercial,cents per kilowatthour,ELEC.PRICE.HI-COM.M,15.36,15.27,15.02,14.77,14.76,14.68,14.96,...,31.76,31.92,32.36,34.45,36.29,35.68,37.10,38.75,40.39,41.20
365,Hawaii : industrial,cents per kilowatthour,ELEC.PRICE.HI-IND.M,12.05,12.01,11.83,11.54,11.41,11.65,11.89,...,28.21,27.96,28.40,30.69,32.14,31.47,32.83,34.49,36.20,37.09
366,Hawaii : transportation,cents per kilowatthour,ELEC.PRICE.HI-TRA.M,--,--,--,--,--,--,--,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
367,Hawaii : other,cents per kilowatthour,ELEC.PRICE.HI-OTH.M,16.50,16.33,16.09,16.31,16.21,17.06,17.69,...,--,--,--,--,--,--,--,--,--,--

In [15]:
df.loc[(df.description == 'Connecticut : residential') ]#& (df.tax == 'I_TAX') & (df.currency == 'EUR')]
# df[df['units'].isnull()]
# df.dropna(subset = ['units'])
df.iloc[:10,:]

,description,units,source key,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,...,Sep 2021,Oct 2021,Nov 2021,Dec 2021,Jan 2022,Feb 2022,Mar 2022,Apr 2022,May 2022,Jun 2022
0,United States,NaN,ELEC.PRICE.US-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,New England,NaN,ELEC.PRICE.NEW-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Connecticut,cents per kilowatthour,ELEC.PRICE.CT-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Connecticut : all sectors,cents per kilowatthour,ELEC.PRICE.CT-ALL.M,9.76,9.06,9.38,9.61,9.57,9.56,9.78,...,19.62,18.90,18.51,18.55,19.90,23.20,20.77,22.22,20.49,21.49
4,Connecticut : residential,cents per kilowatthour,ELEC.PRICE.CT-RES.M,10.70,10.23,10.60,10.87,11.20,11.06,11.00,...,22.42,22.85,21.35,20.85,22.28,26.48,25.61,27.10,24.81,25.43
5,Connecticut : commercial,cents per kilowatthour,ELEC.PRICE.CT-COM.M,9.19,8.73,8.89,9.15,9.45,9.28,9.29,...,17.92,16.91,16.93,16.83,17.79,21.00,17.07,19.34,17.94,19.07
6,Connecticut : industrial,cents per kilowatthour,ELEC.PRICE.CT-IND.M,8.09,7.25,7.53,7.79,7.50,7.48,7.94,...,13.52,13.48,13.29,13.49,14.67,15.20,14.34,14.63,14.30,15.00
7,Connecticut : transportation,cents per kilowatthour,ELEC.PRICE.CT-TRA.M,--,--,--,--,--,--,--,...,11.77,10.17,14.71,14.22,21.18,23.65,18.58,21.90,13.64,14.37
8,Connecticut : other,cents per kilowatthour,ELEC.PRICE.CT-OTH.M,9.22,10.08,10.02,10.74,8.09,12.01,10.56,...,--,--,--,--,--,--,--,--,--,--
9,Maine,cents per kilowatthour,ELEC.PRICE.ME-ALL.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN